### 全局 nickname 黑名单
### 勿修改此段配置 ###
GLOBAL:
  nickname_blacklist:
    education:
      - ['教育','学习','考试','早教','启蒙','室','资料','面授','研修','答疑','规划','升学','考研','教学','公考','考公','题库','中考','考级','考证','法考','考博','备考','学历','托育园','语文']
      - ['数学','英语','考研','托福','雅思','留学','数理化']
    
    medical:
      - ['陪诊','挂号','医疗','门诊','口腔','儿科']
    
    occupation:
      - ['老师','医生','兽医','小助手','助理','专家','经理','公关','教练','律师','搭配师','化妆师','营养师','育儿嫂','中介','月嫂','义工','老板']
    
    house:
      - ['家具','家居','租','房探','探房','房捕快','楼市','翻新','改造','楼盘','家电','软装','深房','京房','沪上房','找房','验房','落户','看房','房产','管家','地产','好房','房屋','室','刷墙','改装']
      - ['安装','清洗','拆改','说房','卖房','卖学区房','选址','讲房','豪宅','地板','装饰','门窗','窗帘','衣橱','卫浴','五金','地板','瓷砖','地板','墙纸','空调','热水器','灯饰','门业','灯具','淋浴']
      - ['厨房','电梯','建筑','美学','空间','户型','渲染','整装','家装','建工','门锁','净水','施工','装修找','HOME','家博会','师傅']
    
    mall:
      - ['百货','壹方城','开市客','壹方天地','万象天地','Cocopark','海岸城','K11','天河城','佛罗伦萨','太古','奥特莱斯','万象城','茂业','金光华','新天地','奥莱','八佰伴','合生汇','恒隆','久光','港汇']
      - ['天环','龙之梦','SKP','缤纷城','大悦城','三里屯','嘉里','万象汇','广场']
    
    brand:
      - ['比亚迪','周生生','奥迪','搜房','周大生','浪琴','奔驰','周大福','链家','新东方','DIESEL','路虎','汤臣倍健','官网','宜家','齐家','顾家','百安居','喜临门','悦享家','源氏','泡泡玛特']
    
    retail:
      - ['箱包','男装','女装','女包','批发','服饰','珠宝','名表','手表','豪车','置业','闲置','轻奢','名品','海购','海淘','童装','奢侈品','奢品','潮牌','美妆','桌球','器材','面膜','美肤','黄金']
      - ['饰品','首饰','腕表','护理','名车','数码','餐厅','瓷器','影像','机票','买房','漂发','穿搭','染发','按摩','折扣','摄影','轰趴','纹身','烫发','团建','和田玉','订制','定制','写真','好物','婚纱']
      - ['文创','造型','婚礼','辅料','高端','面料','发型','特产','文玩','壁纸','手作','打印','美瞳','美甲','美容','拍摄','训练','会员','西服','卖女鞋','卖眼镜','食品','茶业','自营','代购','电商','返佣']
      - ['补贴','打折','甄选','手办']
    
    commerce:
      - ['公司','供应链','民宿','店','柜','商标','企业','集团','品牌','商铺','项目','厂','机构','代理','粤港澳','销','法拍','销','证券','办公','企服','集运','团购','库存','专线','俱乐部','服务','退定']
      - ['画廊','招聘','邮寄','资源','就业','展会','中心','票务','兼职','精选','经纪','会所','仓','价','创业','服务','工作','投资','顾问','渠道','福利','开发','专场','严选','保险','货代','咨询','推荐']
      - ['培训','社','品质','传播','签证','增值','进口','新能源','优选','分享','商城','馆','外包','发货','求职','正品','注册','执照','智能','接单','代办','OEM','商业','铺子','资讯','产品','回收','供应商']
      - ['寄存','财税','铺','售','全国','全球','世界','出国','国际','商务','王者荣耀','上门','专卖','store','乐园','基地','研究所']
    
    car:
      - ['包车','电动车','卖车','汽车','网约车','说车','车行']
    
    industry:
      - ['艺术','Art','家政','移民','设计','Design','DESIGN','贸易','物流','logistic','美业','物业','工程','劳务','科技']
    
    other:
      - ['二手','检测','监理','质检','鉴定','测评','认证','评审','免佣','反佣','资深','高定']



### 宠物配置
PETS:
  domain_nickname_blacklist:
    - ['宠物','萌宠','犬舍','猫舍','会客厅','家']

  content_whitelist:
    - weight: 3
      words:
        - ['银渐层','胖橘','拿破仑','蓝金','矮脚','哈基米','德文','蓝渐层','金渐层','苏格兰折耳','布偶','金吉拉','西高地','缅因','高地','萨摩耶','比熊','柯基','金毛','边牧','泰迪','阿拉斯加','雪纳瑞','博美']
        - ['哈士奇','马尔济斯','拉布拉多','马尔泰','法斗','约克夏','美短','英短','领养']
    - weight: 2
      words:
        - ['喵星人','铲屎官','宠物','萌宠','猫','狗','犬','砂盆','毛孩子','驱虫']

  content_blacklist:
    - ['熊猫','猫眼','加菲猫','胖猫事件','躲猫猫','叮当猫','猫女','凯蒂猫','天猫','汤姆猫','猫人','狗肉','犬夜叉','舔狗','天猫','猫头鹰','挂羊头卖狗肉','机器猫','夜猫子','猫和老鼠','土狗','狗东','龙猫','鸡飞狗跳']
    - ['猫腻','狗肉','狗尾巴草','狗屁','细狗','狗不理','鸡零狗碎','狐朋狗友','猫鼠','打狗棒法','人模狗样','猫山王','黑猫警长','玉桂狗','蒙德里安小猫咪','三丽鸥','森贝儿','小豆泥','线条小狗','妙妙猫','宠物小精灵']
    - ['声色犬马','猫殓','壬猫','文豪野犬','猫叫机','多栋','猫鹿传奇','Kitty','单身狗','黑执事蓝猫','招财猫','鞋狗','狗带','kt猫','帕恰狗','崩坏星穹铁道','山狗','热狗','狗血','哈弗大狗','狗叠','天狗的厨房']
    - ['金丝熊','表情包','壁纸','手机壳','画','设计','文创','美瞳','展会','假睫毛','头像','打工狗','加班狗','科研狗','狗卷','冰箱贴','犬系','猫系','线条狗','泰迪熊','泰迪杯','手链','项链','夹子','鞋','包','手表']
    - ['珠宝','挂件','ai','周边','猫咖','狗仔','穿搭','明星','综艺','联名','手工','DIY','玩偶','娃娃','公仔','保护壳','手办','兔','鼠','鸟','鱼']
  
  cat:
    content_whitelist:
      - weight: 3
        words:
          - ['银渐层','胖橘','拿破仑','蓝金','矮脚','德文','蓝渐层','金渐层','苏格兰折耳','布偶','金吉拉','西高地','缅因','高地','美短','英短','猫']
      - weight: 1
        words:
          - ['喵星人','铲屎官','宠物','萌宠','领养','砂盆','毛孩子','驱虫','哈基米']

    content_blacklist:
      - ['萨摩耶','比熊','柯基','金毛','边牧','泰迪','阿拉斯加','雪纳瑞','博美','哈士奇','马尔济斯','拉布拉多','马尔泰','法斗','约克夏','犬','高地']

  dog:
    content_whitelist:
      - weight: 3
        words:
          - ['萨摩耶','比熊','柯基','金毛','边牧','泰迪','阿拉斯加','雪纳瑞','博美','哈士奇','马尔济斯','拉布拉多','马尔泰','法斗','约克夏','狗','犬','高地']
      - weight: 1
        words:
          - ['宠物','萌宠','领养','砂盆','毛孩子','驱虫']

    content_blacklist:
      - ['银渐层','胖橘','拿破仑','蓝金','矮脚','德文','蓝渐层','金渐层','苏格兰折耳','布偶','金吉拉','西高地','缅因','美短','英短','猫']


### 装修配置
RENOVATE:
  domain_nickname_blacklist:
    - ['北京','上海','广州','深圳','嘉兴','天河','居然','美的','卖']

  content_whitelist:
    - weight: 3
      words:
        - ['装修小白','装修进度','开始装修','装修亲历','动工装修','准备装修','决定装修','装修记录','装修准备','自装日记','新家开工','靠谱工长','木工进场','油工阶段','初步测量','想装修','我的家装','我的装修','瓷砖进场']
        - ['装修踩的坑','装修翻车','装修自装','装修避雷','装修群','装修避坑','装修过程','开始刷漆','盯装修','搞装修','地暖回填','新家自装','硬装完工','装修翻车','自己装修']
    - weight: 2
      words:
        - ['水电改造','水电验收','电路图','管道图','木工','油工','油漆工','瓦工','工长','工头','安装师傅']
        - ['粉刷墙面','返图','打胶','美缝','打柜子','刷墙','贴砖','贴地砖','踢脚线','承重墙','腻子','找平','水电开孔']
        - ['装修效果','装修灵感','装修费用','装修流程','装修计划','装修预算','装修干货','装修合同','装修注意事项','装修问题','装修难题','装修前后对比','装修前后变化','装修日常','家居改造']
        - ['旧屋','旧房','房屋改造','户型改造','建材城','新家装修','开工大吉','装修日记','软装','硬装']
        - ['推拉柜门','吊顶','衣帽间','预留尺寸','验收','干湿分离']
    - weight: 1
      words:
        - ['报价','监理','我家','装修','地板','瓷砖','水电','宜家','客厅','墙面','砍价','浴室','施工','玄关','防水','防潮','洗手台','全包','半包','家居软装']

  content_blacklist:
    - ['拎包入住','看房','买房','建筑设计','民宿','豪宅','轰趴','公寓','租','绘画','出售','好房','餐厅','日料','股东','甲方','土木工程','咖啡','面包','美食','茶楼','酒店','麻辣烫','火锅','店里','烤肉']
    - ['SPA','spa','瑜伽','健身房','房源','笋盘','业主','看展','设计展','设计周','摄影','#新品','急售','押金','手绘','私宅设计','人车分流','南北通透','代画','酒馆','#光影','#别墅','查看更多','灵感']
    - ['特斯拉','#挂画','#装饰画','#意式轻奢','#创意','#经典','承建','#小众','#新房','#地铁口','物流','工作室','自提','转卖','本期','建材展','全包边','甲方','大公开','带你飞','秘籍','宝典','课程','游泳']
    - ['医生','面馆','场馆','汽车','充电桩','老旧小区改造','国学','旅行','招聘','办公室','营业时间','探店','评论','留言','旗舰店']


### 汽车配置
CAR:
  domain_nickname_blacklist:
    - ['特斯拉','丰田','本田','奥迪','雷克萨斯','宾利','兰博基尼','玛莎拉蒂','保时捷','比亚迪','小鹏','蔚来','奔驰','宝马','BMW','BYD','广汽','哈弗','极氪','大众','五菱','长安','岚图']
    - ['搬家','车','艺术','大众','澳康达','汽','卖','轮毂']
    - ['旅游','旅行','度假','上海','北京','广州','开单','爆单','大中华','汽配展','高考','美疗','分析','官方','装备','上迪','指南','宝典','精品师','学姐','学长','上岸','出租','行业']
    - ['解说','钻石','中国','活动','外贸','传媒','财经','赛博','疗师','街拍','国旅','套餐','乐器','交易','奶茶','咖啡','充电','省钱','技术']
  content_whitelist:
    - weight: 3
      words:
        - ['奔驰','宝马','特斯拉','丰田','本田','奥迪','雷克萨斯','宾利','兰博基尼','玛莎拉蒂','保时捷','比亚迪','小鹏','蔚来','吉利汽车','理想汽车','大众汽车','一汽大众','五菱','岚图','广汽','哈弗','极氪']
    - weight: 2
      words:
        - ['轿跑','驾驶','行驶','加油站','驾照','新能源','汽油','交通','四驱','引擎','气囊','发动机','方向盘','安全带','油门','自驾','导航','驱车','提车','买车','开车','高速','落地','收费站','油耗']
        - ['4s店','试驾','预算','贷款','性价比','分期付款','内饰','车载']
    - weight: 1
      words:
        - ['车','合同','保值率','流程','配置','保险']
  content_blacklist:
    - ['摩托车','电动车','机车','单车','自行车','打车','约车','包车','租车','发车','巴车','大巴','车展','赛车','婴儿车','动车','骑车','火车','平衡车','购物车','滑板车','三轮车','助力车']
    - ['学时','考驾照','练车','班车','车站','折叠车','公交车','网约车','汽车博物馆','公路车','翻车','车票','缆车','车商','地铁','索道车','培训','驾校','学车']
    - ['骑行','优惠','比价','买车找我','团队','俱乐部','交通日','批量交付','搬运工','支持分期','到货','0首付','每日推荐','好车','好车不等人','发布会','评论区','直播','最低价','最优选','联系我','后台','汽车分享']
    - ['留言','交付量','政府','政策','老板','专注品质','官宣','训练','服务费','销量','新政','行情','经销商','带你懂车','直营','睡眠','高考','极品报价','批发','墨镜','抽奖','市场','预售','在售','原版','特价','客户']
    - ['免息','私聊','销售日常','销售中心','私信','案例','试点','项目','行业','指导价','一手','行驶里程','公共交通','单词','文化中心','重疾','美食','股市']
    - ['书','摆件','占卜','招聘','思维','就业','文学','产业','广告','模型','电瓶车','中介','出租','工程','装修','房','汽车总动员','租金','育儿','玩具','运势','学历','传媒','要求','写作','联名','艺术','精品','剧']


## 孕妇
PREGNANT:
  domain_nickname_blacklist:
    - ['VIP','写真','摄影','孕妇装','月子服','育儿经','妇儿','催乳师','产后修复','月嫂','月子中心','到家','育儿嫂','阿姨' ,'育儿','妇产科','指导师']

  content_whitelist:
    - weight: 3
      words:
        - ['孕周','糖耐','唐筛']
    - weight: 2
      words:
        - []
    - weight: 1
      words:
        - ['四维','待产包','宫缩','孕反','HCG','小排畸','大排畸','怀孕初期' ,'备孕成功','胎心','NT','孕晚期','孕中期' ,'胎动','怀孕日记','孕期日常']
        - ['胎心监护','产检' ,'顺转剖','胎儿','孕吐','宫颈口','脐带绕颈','羊穿','胎芽','预产期','胎膜','#孕晚期倒计时','卵黄囊','孕期日记']
    - weight: 0.5
      words:
        - ['孕妇','怀孕','足月']
  content_blacklist:
    - ['#孕妈大肚照' ,'#在家拍孕妇照','#孕妇照','#纯欲孕妇照','坐月子','#宝宝用品分享','记录','#妊娠期糖尿病','#AI绘画','妇产医院','孕妈交流群','孕妈群']
    - ['攻略','生产医院','产科医生','四维ai图','#保险','#离婚','#萌娃日常','#育儿干货','#带娃日记','#产后恢复','#子痫前期','#怀孕上班','教你看懂','测评分享']
    - ['推荐[话题]','#无限回购','问题答疑','知识科普','妇幼[话题]','月子日记','#生育津贴','产检报销[话题]','津贴报销[话题]','生孩子医院[话题]','产科[话题]','产科医院[话题]']

## 坐月子的人群
POSTPARTUM:
  domain_nickname_blacklist:
    - ['家政','住家','护工','58到家','保洁','管家','催乳师','产后修复','月嫂','月子中心','到家','育儿嫂','阿姨' ,'育儿']

  content_whitelist:
    - weight: 3
      words:
        - ['坐月子','月子生活','月子餐']
    - weight: 2
      words:
        - []
    - weight: 1
      words:
        - ['月嫂','护工','月子中心','月子会所']
    - weight: -0.5
      words:
        - ['育儿嫂','记录']
        -
  content_blacklist:
    - ['健身','#产后修复','#保姆阿姨','#保姆月嫂','#产后恢复','#产康','个人介绍','擅长技能','#上门产康']


### 消费配置
EXPENSE:
  domain_nickname_blacklist:
    - ['度假','国旅','出差','旅行','酒店','高端','商务','正新鸡排','华莱士','蜜雪冰城','财经','卡地亚','宝格丽','纪梵希','爱马仕','香奈儿','Tiffany']
    - ['工坊','客服','配饰','典当','商贸','专注','高奢','女鞋','包包','纺织','实体','经营','文化','vintage','禁言']
  content_whitelist:
    - weight: 3
      words:
        - ['四季酒店','丽思卡尔顿','文华东方','安缦','悦榕庄','洲际','半岛酒店','瑞吉','W酒店','君悦','文华东方','宝格丽酒店']
        - ['桔子酒店','亚朵','锦江之星']
        - ['头等舱','商务舱','护照','签证']
        - ['潜水','滑雪','骑马','游艇']
        - ['米其林','大董']
        - ['ALDI','LIDL']
        - ['盒马','七鲜','花呗','分期']
  content_blacklist:
    - ['业主']

## 孩子的人群
BABY:
  domain_nickname_blacklist:
    - ['北京','上海','广州','深圳','育儿嫂','旅游','营养师','钢琴','手办','护肤','检测','托育园','烘焙','看置顶','香港','减脂','户外','省钱', '语文','数学','英语','八卦','探房','探房','迪士尼','考公','编辑']
    - ['回关','考研','托福','雅思','指南','儿科','卫浴','减肥','旅行','师','学','广场','音乐','数理化','时尚','潮流','音乐','瘦','中国','官方','招募', '旗舰','知识','影视','AI','有道','汤臣倍健','巧克力','拍照']
    - ['艺术','官网','书','月嫂','乐有家','大峡谷','亲子游','南山','陪玩','幼升小','伴手礼','育儿经','绘本','健康']
  content_whitelist:
    - weight: 3
      words:
        - ['儿子','女儿','孩子','小孩','宝妈','带娃','宝爸','月嫂','婴儿车','骗你生儿子','骗你生女儿','两个孩子','二宝','萌娃','儿童医院',"我家娃", "幼儿园", "小学", "育儿嫂", "新手爸妈", "宝宝发烧"]
        - ["宝宝咳嗽", "亲子", "babycare", "幼升小", "人类幼崽", "男宝宝", "女宝宝", "亲子游", "宝宝周岁", "我家宝宝", "两岁宝宝",'宝宝','奶瓶','纸尿片','奶嘴','纸尿裤','吐奶','磨牙棒','学步']
        - ['早教', '拉拉裤', '隔尿', '口水巾', '爽身粉', '腰凳', '安全座椅', '饭兜', '汗巾', '胎毛', '幼儿', '月龄']

  content_blacklist:
     - ['广告','促销','折扣','买一送一','免费','商务合作','代购','海淘','网红','明星同款','秒杀','特价','团购','福利','网店','官方','旗舰店','化妆品','美妆','时尚','美容','保健品','酒店','闲置','猫']
     - ['瘦身', '减肥','毛孩子','宠物','门票','离婚','学历','谁家','球星','玩偶', '幼师','教育片','开团','电影','时代少年团','墨镜','养生','《','海底捞','引流','阿勒泰','理想身材', '装修干货']
     - ['父母必看','教师职称','剧情','置顶','小编','客户','探店','好小孩子','统计结果','纹眉', '备孕','配货','二手房','深圳','团建','心理咨询','元','房主','音乐剧','案例','自我提升','教资','ppt']
# check single post with user id
     - ['娱乐八卦','看房','提高班','优惠活动','民宿','我小时候','小孩子老人','母婴顾问','字数限制','温馨提示']
  
  infant:
    content_whitelist:
      - weight: 3
        words:
          - ['母乳','哺乳','尿布','产后','月子','吸奶器','分娩','月嫂','胎儿','黄疸','拍嗝','婴儿车', '辅食', '婴儿玩具','纸尿裤','一岁','两岁','1岁','2岁''宝宝喂养', '婴儿','回奶']
          - ['三个月','吃完奶','一周岁','满月','学步','磨牙棒', '疫苗接种','奶粉']
          - ['新生儿', '满月酒', '宝宝睡觉', '宝宝辅食', '宝宝洗澡', '宝宝健康', '宝宝成长', '宝宝护理']
          - ['宝宝用品', '婴儿用品', '婴儿护理', '婴儿健康', '婴儿成长', '婴儿睡眠', '婴儿饮食', '喂奶', '奶瓶']
          - ['宝宝玩具', '早教', '早教玩具', '育儿经验', '育儿知识', '育儿心得', '育儿宝典']
          - ['母婴', '母婴用品', '母婴护理', '母婴健康', '母婴店', '母婴中心', '母婴论坛']
          - ['产后恢复', '产后护理', '产后瘦身', '产后抑郁', '产后修复']
      - weight: 1
        words:
          - ['怀孕', '孕期', '孕妇', '孕妈妈', '孕妈', '孕期检查', '孕期饮食', '孕期护理']
          - ['胎教', '胎动', '胎心', '胎位', '胎儿发育']
          - ['产检', '产房', '剖腹产', '顺产', '早产', '产程', '产后恢复', '产后检查']
    content_blacklist:
      - ['优惠','折扣','促销', '特价', '打折', '买一送一', '限时', '活动', '秒杀', '清仓', '团购', '低价', '批发', '抢购', '满减']
      - ['代理', '分销', '加盟', '合作', '批发价', '代理商', '代理费', '招商', '加盟费']
      - ['广告', '推广', '宣传', '品牌', '新品', '上市', '热销', '爆款', '畅销', '热卖', '销售', '销售额', '销售量', '销量']
      - ['免费', '试用', '赠品', '礼品', '抽奖', '福利', '中奖', '试用装', '试用期']
      - ['旗舰店', '网店', '淘宝', '天猫', '京东', '拼多多', '电商', '微商', '小红书店铺','私xin']

  child:
    content_whitelist:
      - weight: 3
        words:
          - ['幼儿园', '大班', '小班', '中班', '3岁', '三岁', '4岁', '四岁', '5岁', '五岁', '6岁', '六岁', '幼升小', '幼小衔接', '绘本阅读']
          - ['儿童乐园', '托班', '疫苗接种', '奶粉', '早教', '学前班', '亲子阅读', '亲子游戏', '学步车', '早教机', '宝宝餐']
      - weight: 2
        words:
          - ['上幼儿园', '入园', '儿童节', '儿童成长', '儿童健康', '儿童早教', '儿童疫苗', '儿童安全', '儿童玩具', '儿童读物', '儿童绘本']
          - ['儿童故事', '儿童疾病', '儿童心理', '学前教育', '学前活动', '亲子游', '亲子教育', '亲子活动', '亲子关系', '亲子互动', '亲子课堂'] 
          - ['亲子手工', '亲子运动', '育儿经验', '育儿心得', '育儿知识']
      - weight: 1
        words:
          - ['宝宝', '孩子', '小朋友', '小孩子', '宝贝', '儿子', '女儿', '娃', '小孩', '宝贝', '宝贝', '宝贝', '宝贝', '宝贝', '宝贝']
    content_blacklist:
      - ['广告', '推广', '特卖', '折扣', '代购', '优惠券', '促销', '品牌', '商家', '出售', '买卖', '交易', '免费领取', '点击链接', '扫码', '二维码']
      - ['娱乐', '明星', '八卦', '综艺', '电视剧', '电影', '网红', '直播', '美妆', '护肤', '化妆品', '服装', '时尚', '健身', '减肥', '恋爱', '相亲']
      - ['婚姻', '婆媳', '职场', '工作', '招聘', '求职', '创业', '投资', '理财', '股票', '房产', '买房', '租房', '装修', '旅游', '旅游景点', '旅行攻略','成人用品']
      - ['短剧','裁员','满100减15','黑科技','小学','攻略群','哺乳','顺产']

  juvenile:
    content_whitelist:
      - weight: 3
        words:
          - ['青春期', '一年级', '二年级', '三年级', '四年级', '五年级', '六年级', '小升初', '小学', '初中', '初一', '初二', '初三', '重点班',]
          - ['中考', '疫苗接种', '家庭作业', '辅导班', '兴趣班', '补习班', '小学生', '初中生', '课后辅导', '课外活动', '青少年', '青春期教育', '青春期心理']
          - ['青春期健康', '青春期问题', '成长发育', '亲子教育', '亲子沟通', '家庭教育']
      - weight: 2
        words:
          - ['课外书', '校园生活', '班主任', '同学关系', '同学聚会', '班会', '班级活动', '学校活动', '校内活动', '校外活动', '体育课', '运动会']
          - ['兴趣小组', '科学实验', '数学竞赛', '英语角', '作文比赛', '考试复习', '期中考试', '期末考试', '成绩单', '成绩分析', '学习计划', '学习方法']
          - ['学习技巧', '学习习惯', '阅读习惯', '阅读理解', '写作能力', '课外阅读', '课外书籍', '课外读物']
      - weight: 1
        words:
          - ['孩子', '学生', '学习', '成长', '教育', '学校', '课堂', '老师', '家长', '家长会', '家校沟通', '班级', '同学', '考试', '作业', '书包']
          - ['文具', '课本', '教科书', '课程', '学科', '科目', '课本', '教材', '作业本', '笔记本', '文具盒', '铅笔', '橡皮', '尺子', '书籍', '图书馆']
    content_blacklist:
      - ['广告', '推广', '特卖', '折扣', '代购', '优惠券', '促销', '品牌', '商家', '出售', '买卖', '交易', '免费领取', '点击链接', '扫码', '二维码']
      - ['幼儿园', '大班', '小班', '中班', '3岁', '4岁', '5岁', '6岁', '婴幼儿', '宝宝', '新生儿', '0岁', '1岁', '2岁', '幼儿', '婴儿用品']

